import type { Tutor, Review, User, Conversation, Message } from '../types';
import { messagingService, RealtimeMessagePayload } from './messagingService';

const allTutorsData: Tutor[] = [
  {
    id: '1',
    name: 'Dr. Eleanor Vance',
    rating: 4.9,
    reviewCount: 120,
    location: 'New York, NY',
    subjects: ['Physics', 'Calculus', 'Astrophysics'],
    description: 'PhD in Physics with 10+ years of tutoring experience. I make complex topics easy to understand.',
    imageUrl: 'https://picsum.photos/seed/eleanor/200/200',
    experience: 12,
    qualifications: ['PhD in Physics, MIT', 'M.S. in Applied Mathematics'],
    hourlyRate: 75,
    availability: {
      Monday: ['4:00 PM - 8:00 PM'],
      Tuesday: ['4:00 PM - 8:00 PM'],
      Wednesday: ['4:00 PM - 8:00 PM'],
      Thursday: ['4:00 PM - 8:00 PM'],
      Friday: ['4:00 PM - 8:00 PM'],
    },
    isVerified: true,
  },
  {
    id: '2',
    name: 'Samuel Jones',
    rating: 4.8,
    reviewCount: 85,
    location: 'San Francisco, CA',
    subjects: ['Computer Science', 'Python', 'Java'],
    description: 'Software Engineer at a top tech company. Passionate about teaching coding to beginners.',
    imageUrl: 'https://picsum.photos/seed/samuel/200/200',
    experience: 7,
    qualifications: ['B.S. in Computer Science, Stanford', 'Google Certified Developer'],
    hourlyRate: 60,
    availability: {
        Tuesday: ['6:00 PM - 9:00 PM'],
        Thursday: ['6:00 PM - 9:00 PM'],
        Saturday: ['10:00 AM - 4:00 PM'],
    },
    isVerified: true,
  },
  {
    id: '3',
    name: 'Maria Garcia',
    rating: 5.0,
    reviewCount: 210,
    location: 'Miami, FL',
    subjects: ['Spanish', 'French', 'ESL'],
    description: 'Native Spanish speaker with a degree in linguistics. Let\'s make learning a new language fun!',
    imageUrl: 'https://picsum.photos/seed/maria/200/200',
    experience: 8,
    qualifications: ['M.A. in Linguistics', 'Certified Language Instructor'],
    hourlyRate: 45,
    availability: {},
    isVerified: false,
  },
  {
    id: '4',
    name: 'David Chen',
    rating: 4.7,
    reviewCount: 95,
    location: 'Chicago, IL',
    subjects: ['Biology', 'Chemistry', 'MCAT Prep'],
    description: 'Medical student with a knack for breaking down hard science concepts for high school and college students.',
    imageUrl: 'https://picsum.photos/seed/david/200/200',
    experience: 4,
    qualifications: ['B.S. in Biology, UChicago', '99th Percentile MCAT Score'],
    hourlyRate: 65,
    availability: {
        Monday: ['6:00 PM - 10:00 PM'],
        Wednesday: ['6:00 PM - 10:00 PM'],
        Sunday: ['12:00 PM - 5:00 PM'],
    },
    isVerified: true,
  },
    {
    id: '5',
    name: 'Jessica Miller',
    rating: 4.9,
    reviewCount: 150,
    location: 'New York, NY',
    subjects: ['English', 'SAT Prep', 'Literature'],
    description: 'Published author and experienced SAT tutor. I help students craft compelling essays and ace their exams.',
    imageUrl: 'https://picsum.photos/seed/jessica/200/200',
    experience: 9,
    qualifications: ['M.F.A. in Creative Writing, Columbia', 'Certified SAT Instructor'],
    hourlyRate: 70,
    availability: {
        Monday: ['3:00 PM - 7:00 PM'],
        Tuesday: ['3:00 PM - 7:00 PM'],
        Wednesday: ['3:00 PM - 7:00 PM'],
        Thursday: ['3:00 PM - 7:00 PM'],
        Friday: ['3:00 PM - 7:00 PM'],
    },
    isVerified: true,
  },
  {
    id: '6',
    name: 'Ben Carter',
    rating: 4.6,
    reviewCount: 70,
    location: 'San Francisco, CA',
    subjects: ['History', 'Government', 'Debate'],
    description: 'History buff and debate coach. I love helping students develop critical thinking and public speaking skills.',
    imageUrl: 'https://picsum.photos/seed/ben/200/200',
    experience: 6,
    qualifications: ['M.A. in History, UC Berkeley'],
    hourlyRate: 50,
    availability: {
        Saturday: ['1:00 PM - 5:00 PM'],
        Sunday: ['1:00 PM - 5:00 PM'],
    },
    isVerified: false,
  },
  {
    id: '7',
    name: 'Chloe Kim',
    rating: 4.8,
    reviewCount: 110,
    location: 'Los Angeles, CA',
    subjects: ['Art', 'Design', 'Adobe Photoshop'],
    description: 'Professional graphic designer helping aspiring artists build their portfolios and master digital tools.',
    imageUrl: 'https://picsum.photos/seed/chloe/200/200',
    experience: 10,
    qualifications: ['B.F.A. in Graphic Design, RISD', 'Adobe Certified Expert'],
    hourlyRate: 55,
    availability: {
        Monday: ['10:00 AM - 5:00 PM'],
        Wednesday: ['10:00 AM - 5:00 PM'],
        Friday: ['10:00 AM - 5:00 PM'],
    },
    isVerified: true,
  },
  // START: 50 Indian Tutors
  {
    id: '8',
    name: 'Aarav Sharma',
    rating: 4.9,
    reviewCount: 180,
    location: 'Delhi, India',
    subjects: ['Mathematics', 'IIT-JEE Prep', 'Physics'],
    description: 'IIT Delhi graduate with a passion for teaching. I simplify complex problems and build a strong conceptual foundation.',
    imageUrl: 'https://picsum.photos/seed/aarav/200/200',
    experience: 8,
    qualifications: ['B.Tech in Mechanical Engineering, IIT Delhi'],
    hourlyRate: 40,
    availability: { Tuesday: ['5:00 PM - 9:00 PM'], Thursday: ['5:00 PM - 9:00 PM'], Saturday: ['10:00 AM - 6:00 PM'] },
    isVerified: true,
  },
  {
    id: '9',
    name: 'Priya Patel',
    rating: 4.8,
    reviewCount: 155,
    location: 'Mumbai, India',
    subjects: ['Biology', 'NEET Prep', 'Chemistry'],
    description: 'Medical doctor specializing in NEET coaching. My goal is to help you ace your medical entrance exams.',
    imageUrl: 'https://picsum.photos/seed/priya/200/200',
    experience: 10,
    qualifications: ['MBBS, Grant Medical College', 'M.D. in General Medicine'],
    hourlyRate: 50,
    availability: { Monday: ['6:00 PM - 10:00 PM'], Wednesday: ['6:00 PM - 10:00 PM'], Sunday: ['11:00 AM - 5:00 PM'] },
    isVerified: true,
  },
  {
    id: '10',
    name: 'Rohan Gupta',
    rating: 4.7,
    reviewCount: 110,
    location: 'Bangalore, India',
    subjects: ['Computer Science', 'Data Structures', 'Algorithms'],
    description: 'Software architect at a leading MNC. I offer practical, industry-relevant coding knowledge.',
    imageUrl: 'https://picsum.photos/seed/rohan/200/200',
    experience: 12,
    qualifications: ['M.Tech in Computer Science, IISc Bangalore'],
    hourlyRate: 60,
    availability: { Saturday: ['9:00 AM - 1:00 PM'], Sunday: ['9:00 AM - 1:00 PM'] },
    isVerified: false,
  },
  {
    id: '11',
    name: 'Ananya Reddy',
    rating: 5.0,
    reviewCount: 220,
    location: 'Hyderabad, India',
    subjects: ['English Literature', 'Creative Writing', 'IELTS Prep'],
    description: 'Gold medalist in English Literature. I help students develop a love for the language and excel in exams.',
    imageUrl: 'https://picsum.photos/seed/ananya/200/200',
    experience: 7,
    qualifications: ['M.A. in English Literature, University of Hyderabad', 'CELTA Certified'],
    hourlyRate: 35,
    availability: { Monday: ['4:00 PM - 7:00 PM'], Friday: ['4:00 PM - 7:00 PM'] },
    isVerified: true,
  },
  {
    id: '12',
    name: 'Vikram Singh',
    rating: 4.8,
    reviewCount: 130,
    location: 'Jaipur, India',
    subjects: ['History', 'Political Science', 'UPSC Prep'],
    description: 'Former civil servant providing comprehensive guidance for UPSC aspirants.',
    imageUrl: 'https://picsum.photos/seed/vikram/200/200',
    experience: 15,
    qualifications: ['M.A. in History, Delhi University', 'Cleared UPSC Civil Services Exam'],
    hourlyRate: 55,
    availability: { Wednesday: ['3:00 PM - 8:00 PM'], Saturday: ['10:00 AM - 4:00 PM'] },
    isVerified: true,
  },
  {
    id: '13',
    name: 'Isha Nair',
    rating: 4.9,
    reviewCount: 95,
    location: 'Chennai, India',
    subjects: ['Accountancy', 'Business Studies', 'Economics'],
    description: 'Chartered Accountant with a flair for teaching commerce subjects for classes 11, 12 and B.Com.',
    imageUrl: 'https://picsum.photos/seed/isha/200/200',
    experience: 6,
    qualifications: ['Chartered Accountant (ICAI)', 'M.Com, University of Madras'],
    hourlyRate: 45,
    availability: { Tuesday: ['6:00 PM - 9:00 PM'], Thursday: ['6:00 PM - 9:00 PM'] },
    isVerified: false,
  },
  {
    id: '14',
    name: 'Arjun Das',
    rating: 4.7,
    reviewCount: 140,
    location: 'Kolkata, India',
    subjects: ['Physics', 'Chemistry', 'WBJEE'],
    description: 'Professor at a renowned college, passionate about helping students with entrance exam preparations.',
    imageUrl: 'https://picsum.photos/seed/arjun/200/200',
    experience: 20,
    qualifications: ['Ph.D. in Chemistry, Jadavpur University'],
    hourlyRate: 50,
    availability: { Sunday: ['10:00 AM - 2:00 PM'] },
    isVerified: true,
  },
  {
    id: '15',
    name: 'Saanvi Joshi',
    rating: 4.9,
    reviewCount: 190,
    location: 'Pune, India',
    subjects: ['German', 'French', 'Foreign Languages'],
    description: 'Certified foreign language expert. I make learning a new language an immersive and fun experience.',
    imageUrl: 'https://picsum.photos/seed/saanvi/200/200',
    experience: 9,
    qualifications: ['C1 Level Certified in German and French'],
    hourlyRate: 40,
    availability: { Monday: ['10:00 AM - 2:00 PM'], Wednesday: ['10:00 AM - 2:00 PM'] },
    isVerified: true,
  },
  {
    id: '16',
    name: 'Kabir Khan',
    rating: 4.6,
    reviewCount: 80,
    location: 'Lucknow, India',
    subjects: ['Urdu', 'History', 'Poetry'],
    description: 'An enthusiast of language and history, offering deep insights into Urdu literature and Mughal history.',
    imageUrl: 'https://picsum.photos/seed/kabir/200/200',
    experience: 11,
    qualifications: ['M.A. in History, Aligarh Muslim University'],
    hourlyRate: 30,
    availability: {},
    isVerified: false,
  },
  {
    id: '17',
    name: 'Diya Mehta',
    rating: 4.8,
    reviewCount: 165,
    location: 'Ahmedabad, India',
    subjects: ['CAT Prep', 'Quantitative Aptitude', 'Data Interpretation'],
    description: 'IIM Ahmedabad alumnus, helping MBA aspirants crack the CAT with proven strategies and shortcuts.',
    imageUrl: 'https://picsum.photos/seed/diya/200/200',
    experience: 5,
    qualifications: ['PGDM, IIM Ahmedabad', '99.8 percentile in CAT'],
    hourlyRate: 70,
    availability: { Saturday: ['2:00 PM - 8:00 PM'], Sunday: ['2:00 PM - 8:00 PM'] },
    isVerified: true,
  },
  {
    id: '18',
    name: 'Advik Iyer',
    rating: 4.9,
    reviewCount: 135,
    location: 'Bangalore, India',
    subjects: ['Robotics', 'Python', 'Machine Learning'],
    description: 'Robotics engineer making AI and ML accessible to students. Hands-on, project-based learning.',
    imageUrl: 'https://picsum.photos/seed/advik/200/200',
    experience: 6,
    qualifications: ['M.S in Robotics, Carnegie Mellon University', 'B.Tech, IIT Madras'],
    hourlyRate: 80,
    availability: { Friday: ['7:00 PM - 10:00 PM'], Saturday: ['11:00 AM - 4:00 PM'] },
    isVerified: true,
  },
  {
    id: '19',
    name: 'Zara Begum',
    rating: 4.7,
    reviewCount: 90,
    location: 'Hyderabad, India',
    subjects: ['Biotechnology', 'Genetics', 'Biology'],
    description: 'Research scientist with a passion for teaching advanced topics in biology.',
    imageUrl: 'https://picsum.photos/seed/zara/200/200',
    experience: 7,
    qualifications: ['Ph.D. in Biotechnology, Osmania University'],
    hourlyRate: 55,
    availability: { Tuesday: ['5:00 PM - 8:00 PM'] },
    isVerified: false,
  },
  {
    id: '20',
    name: 'Shaurya Chauhan',
    rating: 4.8,
    reviewCount: 115,
    location: 'Gurgaon, India',
    subjects: ['GMAT Prep', 'Verbal Ability', 'Critical Reasoning'],
    description: 'Experienced GMAT trainer with a track record of helping students achieve 700+ scores.',
    imageUrl: 'https://picsum.photos/seed/shaurya/200/200',
    experience: 10,
    qualifications: ['GMAT Score: 760', 'MBA, MDI Gurgaon'],
    hourlyRate: 65,
    availability: { Saturday: ['9:00 AM - 12:00 PM'], Sunday: ['9:00 AM - 12:00 PM'] },
    isVerified: true,
  },
  {
    id: '21',
    name: 'Mira Desai',
    rating: 5.0,
    reviewCount: 250,
    location: 'Mumbai, India',
    subjects: ['Psychology', 'Sociology', 'CBSE Board'],
    description: 'Counseling psychologist making social sciences relatable and interesting for school students.',
    imageUrl: 'https://picsum.photos/seed/mira/200/200',
    experience: 8,
    qualifications: ['M.A. in Clinical Psychology, TISS Mumbai'],
    hourlyRate: 40,
    availability: { Monday: ['11:00 AM - 3:00 PM'], Wednesday: ['11:00 AM - 3:00 PM'] },
    isVerified: true,
  },
  {
    id: '22',
    name: 'Vivaan Malhotra',
    rating: 4.7,
    reviewCount: 105,
    location: 'Chandigarh, India',
    subjects: ['Legal Studies', 'CLAT Prep', 'Logic'],
    description: 'NLU graduate helping law aspirants navigate the CLAT and other law entrance exams.',
    imageUrl: 'https://picsum.photos/seed/vivaan/200/200',
    experience: 4,
    qualifications: ['B.A. LL.B (Hons.), NLU Delhi'],
    hourlyRate: 50,
    availability: { Friday: ['6:00 PM - 9:00 PM'], Saturday: ['10:00 AM - 3:00 PM'] },
    isVerified: true,
  },
  {
    id: '23',
    name: 'Kiara Sen',
    rating: 4.8,
    reviewCount: 170,
    location: 'Kolkata, India',
    subjects: ['Fine Arts', 'Painting', 'Sketching'],
    description: 'Professional artist offering personalized art lessons to nurture creativity in students of all ages.',
    imageUrl: 'https://picsum.photos/seed/kiara/200/200',
    experience: 12,
    qualifications: ['MFA, Government College of Art & Craft, Kolkata'],
    hourlyRate: 35,
    availability: { Saturday: ['1:00 PM - 5:00 PM'], Sunday: ['1:00 PM - 5:00 PM'] },
    isVerified: false,
  },
  {
    id: '24',
    name: 'Reyansh Kumar',
    rating: 4.9,
    reviewCount: 145,
    location: 'Patna, India',
    subjects: ['Mathematics', 'SSC CGL', 'Banking Exams'],
    description: 'Expert in quantitative aptitude for government job examinations. Simplified tricks for complex calculations.',
    imageUrl: 'https://picsum.photos/seed/reyansh/200/200',
    experience: 9,
    qualifications: ['M.Sc in Mathematics, Patna University'],
    hourlyRate: 30,
    availability: { Tuesday: ['4:00 PM - 8:00 PM'], Thursday: ['4:00 PM - 8:00 PM'] },
    isVerified: true,
  },
  {
    id: '25',
    name: 'Aisha Rao',
    rating: 4.8,
    reviewCount: 125,
    location: 'Pune, India',
    subjects: ['Java', 'Spring Boot', 'Microservices'],
    description: 'Senior Java Developer passionate about teaching real-world application development.',
    imageUrl: 'https://picsum.photos/seed/aisha/200/200',
    experience: 10,
    qualifications: ['B.E. in Information Technology, COEP'],
    hourlyRate: 60,
    availability: { Saturday: ['6:00 PM - 10:00 PM'] },
    isVerified: true,
  },
  {
    id: '26',
    name: 'Ishaan Trivedi',
    rating: 4.7,
    reviewCount: 100,
    location: 'Indore, India',
    subjects: ['Sanskrit', 'Vedic Maths', 'Philosophy'],
    description: 'PhD in Sanskrit dedicated to preserving and teaching ancient Indian knowledge systems.',
    imageUrl: 'https://picsum.photos/seed/ishaan/200/200',
    experience: 15,
    qualifications: ['Ph.D. in Sanskrit, Devi Ahilya Vishwavidyalaya'],
    hourlyRate: 40,
    availability: { Monday: ['9:00 AM - 12:00 PM'], Friday: ['9:00 AM - 12:00 PM'] },
    isVerified: false,
  },
  {
    id: '27',
    name: 'Myra Aggarwal',
    rating: 5.0,
    reviewCount: 200,
    location: 'Delhi, India',
    subjects: ['Fashion Design', 'Textile Design', 'NIFT Prep'],
    description: 'NIFT graduate and fashion designer, mentoring the next generation of creative minds.',
    imageUrl: 'https://picsum.photos/seed/myra/200/200',
    experience: 7,
    qualifications: ['B.Des in Fashion Design, NIFT Delhi'],
    hourlyRate: 55,
    availability: { Wednesday: ['2:00 PM - 6:00 PM'], Thursday: ['2:00 PM - 6:00 PM'] },
    isVerified: true,
  },
   {
    id: '28',
    name: 'Neel Menon',
    rating: 4.8,
    reviewCount: 110,
    location: 'Kochi, India',
    subjects: ['Geography', 'Environmental Science', 'ICSE Board'],
    description: 'Passionate educator focused on making geography and environmental studies engaging and relevant.',
    imageUrl: 'https://picsum.photos/seed/neel/200/200',
    experience: 9,
    qualifications: ['M.Sc in Geography, Cochin University'],
    hourlyRate: 35,
    availability: { Monday: ['5:00 PM - 8:00 PM'], Wednesday: ['5:00 PM - 8:00 PM'] },
    isVerified: true,
  },
  {
    id: '29',
    name: 'Tara Subramanian',
    rating: 4.9,
    reviewCount: 185,
    location: 'Chennai, India',
    subjects: ['Carnatic Music', 'Violin', 'Music Theory'],
    description: 'Professional Carnatic vocalist and violinist from a renowned musical family, offering lessons for all levels.',
    imageUrl: 'https://picsum.photos/seed/tara/200/200',
    experience: 18,
    qualifications: ['Vidwan title from Madras Music Academy'],
    hourlyRate: 50,
    availability: { Saturday: ['9:00 AM - 5:00 PM'], Sunday: ['9:00 AM - 5:00 PM'] },
    isVerified: true,
  },
  {
    id: '30',
    name: 'Arnav Choudhury',
    rating: 4.7,
    reviewCount: 95,
    location: 'Guwahati, India',
    subjects: ['Social Studies', 'Assamese', 'History'],
    description: 'Experienced school teacher specializing in social sciences for middle and high school students.',
    imageUrl: 'https://picsum.photos/seed/arnav/200/200',
    experience: 14,
    qualifications: ['M.A. in History, Gauhati University', 'B.Ed'],
    hourlyRate: 25,
    availability: { Tuesday: ['4:00 PM - 7:00 PM'], Thursday: ['4:00 PM - 7:00 PM'] },
    isVerified: false,
  },
  {
    id: '31',
    name: 'Anika Kapoor',
    rating: 4.8,
    reviewCount: 160,
    location: 'Noida, India',
    subjects: ['Digital Marketing', 'SEO', 'Social Media Marketing'],
    description: 'Digital marketing strategist helping students and professionals build skills for the modern workplace.',
    imageUrl: 'https://picsum.photos/seed/anika/200/200',
    experience: 6,
    qualifications: ['Google Ads Certified', 'HubSpot Inbound Marketing Certified'],
    hourlyRate: 60,
    availability: { Monday: ['7:00 PM - 10:00 PM'], Wednesday: ['7:00 PM - 10:00 PM'] },
    isVerified: true,
  },
  {
    id: '32',
    name: 'Dhruv Bansal',
    rating: 4.9,
    reviewCount: 175,
    location: 'Delhi, India',
    subjects: ['Stock Market', 'Financial Modeling', 'Economics'],
    description: 'Ex-investment banker demystifying finance and stock market investing for beginners and enthusiasts.',
    imageUrl: 'https://picsum.photos/seed/dhruv/200/200',
    experience: 10,
    qualifications: ['MBA in Finance, FMS Delhi', 'NSE Certified Market Professional'],
    hourlyRate: 75,
    availability: { Saturday: ['10:00 AM - 1:00 PM'] },
    isVerified: true,
  },
  {
    id: '33',
    name: 'Samaira Varma',
    rating: 4.8,
    reviewCount: 140,
    location: 'Bangalore, India',
    subjects: ['User Experience (UX)', 'UI Design', 'Figma'],
    description: 'Lead UX designer at a startup, providing practical training in UI/UX design principles and tools.',
    imageUrl: 'https://picsum.photos/seed/samaira/200/200',
    experience: 8,
    qualifications: ['Certified Usability Analyst (CUA)', 'B.Des from NID'],
    hourlyRate: 65,
    availability: { Tuesday: ['8:00 PM - 10:00 PM'], Thursday: ['8:00 PM - 10:00 PM'] },
    isVerified: true,
  },
  {
    id: '34',
    name: 'Krishna Pillai',
    rating: 4.7,
    reviewCount: 115,
    location: 'Trivandrum, India',
    subjects: ['Malayalam', 'Kerala History', 'Literature'],
    description: 'Writer and historian specializing in Malayalam literature and the history of Kerala.',
    imageUrl: 'https://picsum.photos/seed/krishna/200/200',
    experience: 20,
    qualifications: ['M.A. in Malayalam Literature, University of Kerala'],
    hourlyRate: 30,
    availability: {},
    isVerified: false,
  },
  {
    id: '35',
    name: 'Lavanya Murthy',
    rating: 4.9,
    reviewCount: 195,
    location: 'Mysore, India',
    subjects: ['Yoga', 'Meditation', 'Wellness'],
    description: 'Certified yoga instructor from the traditional Mysore school, offering classes for physical and mental well-being.',
    imageUrl: 'https://picsum.photos/seed/lavanya/200/200',
    experience: 12,
    qualifications: ['500-Hour Certified Yoga Teacher (Yoga Alliance)'],
    hourlyRate: 25,
    availability: { Monday: ['6:00 AM - 9:00 AM'], Wednesday: ['6:00 AM - 9:00 AM'], Friday: ['6:00 AM - 9:00 AM'] },
    isVerified: true,
  },
  {
    id: '36',
    name: 'Rudra Pratap Singh',
    rating: 4.8,
    reviewCount: 120,
    location: 'Varanasi, India',
    subjects: ['Hindustani Classical', 'Vocal Music', 'Tabla'],
    description: 'A musician from the Banaras Gharana, teaching the nuances of Hindustani classical music.',
    imageUrl: 'https://picsum.photos/seed/rudra/200/200',
    experience: 25,
    qualifications: ['Sangeet Praveen from Prayag Sangeet Samiti'],
    hourlyRate: 45,
    availability: { Sunday: ['10:00 AM - 6:00 PM'] },
    isVerified: true,
  },
  {
    id: '37',
    name: 'Siya Kulkarni',
    rating: 4.7,
    reviewCount: 130,
    location: 'Nagpur, India',
    subjects: ['Marathi', 'History', 'State Board'],
    description: 'Experienced teacher for Maharashtra State Board curriculum, specializing in Marathi and Social Studies.',
    imageUrl: 'https://picsum.photos/seed/siya/200/200',
    experience: 16,
    qualifications: ['M.A. in Marathi, Nagpur University', 'B.Ed'],
    hourlyRate: 25,
    availability: { Monday: ['4:00 PM - 7:00 PM'], Tuesday: ['4:00 PM - 7:00 PM'], Wednesday: ['4:00 PM - 7:00 PM'] },
    isVerified: false,
  },
  {
    id: '38',
    name: 'Parth Bhatt',
    rating: 4.9,
    reviewCount: 150,
    location: 'Surat, India',
    subjects: ['Gujarati', 'Accountancy', 'GSEB Board'],
    description: 'Dedicated tutor for Gujarat State Board students with a focus on Commerce subjects.',
    imageUrl: 'https://picsum.photos/seed/parth/200/200',
    experience: 10,
    qualifications: ['M.Com, Veer Narmad South Gujarat University'],
    hourlyRate: 30,
    availability: { Tuesday: ['5:00 PM - 9:00 PM'], Thursday: ['5:00 PM - 9:00 PM'] },
    isVerified: true,
  },
  {
    id: '39',
    name: 'Aditi Biswas',
    rating: 4.8,
    reviewCount: 160,
    location: 'Kolkata, India',
    subjects: ['Bengali', 'Rabindra Sangeet', 'Literature'],
    description: 'Visva-Bharati alumna passionate about teaching Bengali literature and Rabindra Sangeet.',
    imageUrl: 'https://picsum.photos/seed/aditi/200/200',
    experience: 9,
    qualifications: ['M.A. in Bengali, Visva-Bharati University'],
    hourlyRate: 35,
    availability: { Saturday: ['11:00 AM - 4:00 PM'] },
    isVerified: true,
  },
  {
    id: '40',
    name: 'Kian Sharma',
    rating: 4.7,
    reviewCount: 85,
    location: 'Shimla, India',
    subjects: ['Environmental Science', 'Botany', 'Zoology'],
    description: 'Ecologist and researcher, offering tutoring for university-level environmental science courses.',
    imageUrl: 'https://picsum.photos/seed/kian/200/200',
    experience: 7,
    qualifications: ['Ph.D. in Ecology, Himachal Pradesh University'],
    hourlyRate: 50,
    availability: { Monday: ['10:00 AM - 1:00 PM'] },
    isVerified: false,
  },
  {
    id: '41',
    name: 'Anvi Singh Rathore',
    rating: 4.9,
    reviewCount: 190,
    location: 'Jodhpur, India',
    subjects: ['Photography', 'Photo Editing', 'Videography'],
    description: 'Award-winning photographer teaching the art and technique of capturing stunning visuals.',
    imageUrl: 'https://picsum.photos/seed/anvi/200/200',
    experience: 11,
    qualifications: ['Diploma in Photography from Light and Life Academy'],
    hourlyRate: 55,
    availability: { Sunday: ['1:00 PM - 6:00 PM'] },
    isVerified: true,
  },
  {
    id: '42',
    name: 'Devansh Reddy',
    rating: 4.8,
    reviewCount: 140,
    location: 'Visakhapatnam, India',
    subjects: ['Naval Architecture', 'Marine Engineering', 'Physics'],
    description: 'Marine engineer from Andhra University, providing specialized tutoring for engineering students.',
    imageUrl: 'https://picsum.photos/seed/devansh/200/200',
    experience: 8,
    qualifications: ['B.E. in Naval Architecture, Andhra University'],
    hourlyRate: 60,
    availability: { Friday: ['6:00 PM - 9:00 PM'], Saturday: ['6:00 PM - 9:00 PM'] },
    isVerified: true,
  },
  {
    id: '43',
    name: 'Shanaya Ali',
    rating: 4.7,
    reviewCount: 110,
    location: 'Bhopal, India',
    subjects: ['Public Speaking', 'Debate', 'Personality Development'],
    description: 'Communications coach helping students and professionals improve their confidence and public speaking skills.',
    imageUrl: 'https://picsum.photos/seed/shanaya/200/200',
    experience: 9,
    qualifications: ['Certified Corporate Trainer'],
    hourlyRate: 45,
    availability: { Tuesday: ['6:00 PM - 8:00 PM'] },
    isVerified: false,
  },
  {
    id: '44',
    name: 'Aryan Joshi',
    rating: 4.9,
    reviewCount: 180,
    location: 'Dehradun, India',
    subjects: ['Geology', 'Geography', 'Earth Sciences'],
    description: 'Geologist from Wadia Institute of Himalayan Geology, making earth sciences fascinating for students.',
    imageUrl: 'https://picsum.photos/seed/aryan/200/200',
    experience: 10,
    qualifications: ['M.Sc in Geology, HNB Garhwal University'],
    hourlyRate: 50,
    availability: { Wednesday: ['4:00 PM - 7:00 PM'] },
    isVerified: true,
  },
  {
    id: '45',
    name: 'Rhea Chakraborty',
    rating: 4.8,
    reviewCount: 125,
    location: 'Ranchi, India',
    subjects: ['Anthropology', 'Tribal Studies', 'Sociology'],
    description: 'Researcher focusing on tribal cultures of India, offering unique insights for anthropology students.',
    imageUrl: 'https://picsum.photos/seed/rhea/200/200',
    experience: 6,
    qualifications: ['Ph.D. in Anthropology, Ranchi University'],
    hourlyRate: 40,
    availability: { Saturday: ['10:00 AM - 2:00 PM'] },
    isVerified: true,
  },
  {
    id: '46',
    name: 'Ayaan Khan',
    rating: 4.7,
    reviewCount: 105,
    location: 'Srinagar, India',
    subjects: ['Persian', 'Kashmiri', 'Sufi Literature'],
    description: 'Scholar of Persian and Kashmiri literature, exploring the rich poetic traditions of the valley.',
    imageUrl: 'https://picsum.photos/seed/ayaan/200/200',
    experience: 18,
    qualifications: ['M.A. in Persian, University of Kashmir'],
    hourlyRate: 35,
    availability: {},
    isVerified: false,
  },
  {
    id: '47',
    name: 'Jiya Kaur',
    rating: 4.9,
    reviewCount: 165,
    location: 'Amritsar, India',
    subjects: ['Punjabi', 'History of Punjab', 'Gurbani'],
    description: 'Passionate teacher of Punjabi language and Sikh history, helping students connect with their heritage.',
    imageUrl: 'https://picsum.photos/seed/jiya/200/200',
    experience: 12,
    qualifications: ['M.A. in Punjabi, Guru Nanak Dev University'],
    hourlyRate: 30,
    availability: { Monday: ['3:00 PM - 6:00 PM'], Wednesday: ['3:00 PM - 6:00 PM'] },
    isVerified: true,
  },
  {
    id: '48',
    name: 'Yash Vardhan',
    rating: 4.8,
    reviewCount: 135,
    location: 'Kota, India',
    subjects: ['Organic Chemistry', 'IIT-JEE Advanced', 'Problem Solving'],
    description: 'Veteran chemistry faculty from Kota, specializing in advanced problem-solving for JEE aspirants.',
    imageUrl: 'https://picsum.photos/seed/yash/200/200',
    experience: 15,
    qualifications: ['M.Sc in Chemistry, University of Rajasthan'],
    hourlyRate: 80,
    availability: { Monday: ['6:00 PM - 10:00 PM'], Tuesday: ['6:00 PM - 10:00 PM'], Thursday: ['6:00 PM - 10:00 PM'] },
    isVerified: true,
  },
  {
    id: '49',
    name: 'Fatima Sheikh',
    rating: 4.9,
    reviewCount: 155,
    location: 'Aligarh, India',
    subjects: ['Political Science', 'International Relations', 'History'],
    description: 'AMU gold-medalist offering in-depth classes on political theory and international affairs.',
    imageUrl: 'https://picsum.photos/seed/fatima/200/200',
    experience: 7,
    qualifications: ['M.A. in Political Science, Aligarh Muslim University'],
    hourlyRate: 45,
    availability: { Sunday: ['12:00 PM - 5:00 PM'] },
    isVerified: true,
  },
  {
    id: '50',
    name: 'Laksh Kumar',
    rating: 4.7,
    reviewCount: 110,
    location: 'Bhubaneswar, India',
    subjects: ['Odia', 'History', 'OPSC Prep'],
    description: 'Dedicated educator for Odia language and literature, also providing guidance for state civil service exams.',
    imageUrl: 'https://picsum.photos/seed/laksh/200/200',
    experience: 13,
    qualifications: ['M.A. in Odia, Utkal University', 'B.Ed'],
    hourlyRate: 30,
    availability: { Tuesday: ['5:00 PM - 8:00 PM'] },
    isVerified: false,
  },
  {
    id: '51',
    name: 'Zoya Akhtar',
    rating: 4.8,
    reviewCount: 180,
    location: 'Mumbai, India',
    subjects: ['Screenwriting', 'Film Studies', 'Creative Writing'],
    description: 'Independent filmmaker and writer, teaching the art of storytelling for the screen.',
    imageUrl: 'https://picsum.photos/seed/zoya/200/200',
    experience: 9,
    qualifications: ['Diploma in Screenwriting, FTII Pune'],
    hourlyRate: 70,
    availability: { Friday: ['4:00 PM - 8:00 PM'] },
    isVerified: true,
  },
  {
    id: '52',
    name: 'Rohit Mehra',
    rating: 4.9,
    reviewCount: 200,
    location: 'Kanpur, India',
    subjects: ['Chemical Engineering', 'GATE Prep', 'Thermodynamics'],
    description: 'IIT Kanpur alumnus helping chemical engineering students master core subjects and crack GATE.',
    imageUrl: 'https://picsum.photos/seed/rohitm/200/200',
    experience: 11,
    qualifications: ['M.Tech in Chemical Engineering, IIT Kanpur'],
    hourlyRate: 65,
    availability: { Saturday: ['9:00 AM - 1:00 PM'], Sunday: ['9:00 AM - 1:00 PM'] },
    isVerified: true,
  },
  {
    id: '53',
    name: 'Suresh Iyer',
    rating: 4.8,
    reviewCount: 150,
    location: 'Madurai, India',
    subjects: ['Tamil', 'History', 'TNPSC Prep'],
    description: 'Experienced Tamil teacher providing coaching for the Tamil Nadu Public Service Commission exams.',
    imageUrl: 'https://picsum.photos/seed/suresh/200/200',
    experience: 22,
    qualifications: ['M.A., M.Phil in Tamil, Madurai Kamaraj University'],
    hourlyRate: 35,
    availability: { Monday: ['5:00 PM - 9:00 PM'], Wednesday: ['5:00 PM - 9:00 PM'] },
    isVerified: true,
  },
  {
    id: '54',
    name: 'Esha Gupta',
    rating: 4.7,
    reviewCount: 130,
    location: 'Goa, India',
    subjects: ['Hospitality Management', 'Tourism', 'Event Management'],
    description: 'Hospitality industry veteran teaching the nuances of hotel and event management.',
    imageUrl: 'https://picsum.photos/seed/esha/200/200',
    experience: 17,
    qualifications: ['B.Sc in Hospitality and Hotel Administration, IHM Goa'],
    hourlyRate: 50,
    availability: { Tuesday: ['10:00 AM - 2:00 PM'] },
    isVerified: false,
  },
  {
    id: '55',
    name: 'Nikhil Gowda',
    rating: 4.9,
    reviewCount: 170,
    location: 'Bangalore, India',
    subjects: ['Kannada', 'Karnataka History', 'KPSC Prep'],
    description: 'Passionate tutor for Kannada language and Karnataka history, with a focus on state civil services.',
    imageUrl: 'https://picsum.photos/seed/nikhil/200/200',
    experience: 10,
    qualifications: ['M.A. in Kannada, Bangalore University'],
    hourlyRate: 35,
    availability: { Thursday: ['6:00 PM - 9:00 PM'], Saturday: ['10:00 AM - 2:00 PM'] },
    isVerified: true,
  },
  {
    id: '56',
    name: 'Pooja Tiwari',
    rating: 4.8,
    reviewCount: 190,
    location: 'Allahabad, India',
    subjects: ['Hindi Literature', 'Poetry', 'UGC-NET Prep'],
    description: 'PhD scholar from Allahabad University, specializing in modern Hindi literature for university students.',
    imageUrl: 'https://picsum.photos/seed/pooja/200/200',
    experience: 8,
    qualifications: ['Ph.D. (Pursuing) in Hindi, University of Allahabad', 'JRF Qualified'],
    hourlyRate: 40,
    availability: { Monday: ['2:00 PM - 6:00 PM'], Thursday: ['2:00 PM - 6:00 PM'] },
    isVerified: true,
  },
  {
    id: '57',
    name: 'Anjali Menon',
    rating: 5.0,
    reviewCount: 210,
    location: 'Kochi, India',
    subjects: ['Bharatanatyam', 'Mohiniyattam', 'Dance Theory'],
    description: 'Accomplished classical dancer from the Kalamandalam tradition, offering authentic dance training.',
    imageUrl: 'https://picsum.photos/seed/anjalim/200/200',
    experience: 20,
    qualifications: ['Diploma in Mohiniyattam, Kerala Kalamandalam'],
    hourlyRate: 50,
    availability: { Saturday: ['3:00 PM - 7:00 PM'], Sunday: ['10:00 AM - 2:00 PM'] },
    isVerified: true,
  },
  // END: 50 Indian Tutors
];

const allReviewsData: Review[] = [
    { id: 'r1', studentName: 'Alex Johnson', studentImageUrl: 'https://picsum.photos/seed/alex/100/100', text: 'Dr. Vance made physics so much more approachable. My grades have improved significantly!' },
    { id: 'r2', studentName: 'Brenda Smith', studentImageUrl: 'https://picsum.photos/seed/brenda/100/100', text: 'Samuel is an amazing coding tutor. I went from knowing nothing to building my own web app.' },
    { id: 'r3', studentName: 'Carlos Diaz', studentImageUrl: 'https://picsum.photos/seed/carlos/100/100', text: 'Learning Spanish with Maria was fantastic! Her lessons are engaging and effective.' },
    { id: 'r4', studentName: 'Sophia Lee', studentImageUrl: 'https://picsum.photos/seed/sophia/100/100', text: 'David\'s MCAT prep was a game-changer. His strategies are top-notch and easy to follow.' },
    { id: 'r5', studentName: 'Ethan Williams', studentImageUrl: 'https://picsum.photos/seed/ethan/100/100', text: 'My SAT score went up 200 points thanks to Jessica. Highly recommend!' },
    { id: 'r6', studentName: 'Olivia Brown', studentImageUrl: 'https://picsum.photos/seed/olivia/100/100', text: 'Ben made history my favorite subject. His passion for the material is contagious.' },
];

const mockUsers: User[] = [
    { id: 'student1', name: 'Test Student', imageUrl: 'https://picsum.photos/seed/student/100/100'},
    ...allTutorsData.map(t => ({ id: t.id, name: t.name, imageUrl: t.imageUrl }))
];

let mockConversations: Conversation[] = [
    {
        id: 'c1',
        participants: [mockUsers[0], mockUsers[1]],
        messages: [
            { id: 'm1', senderId: 'student1', text: 'Hi Dr. Vance, I am interested in Physics tutoring.', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString() },
            { id: 'm2', senderId: '1', text: 'Hello! I would be happy to help. When are you available?', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 23).toISOString() },
        ],
    }
];

// Simulate API delay
const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

const addMessage = (data: { senderId: string; receiverId: string; text: string }): { newMessage: Message, conversation: Conversation } => {
    const { senderId, receiverId, text } = data;
    
    let conversation = mockConversations.find(c => 
        c.participants.length === 2 &&
        c.participants.some(p => p.id === senderId) && 
        c.participants.some(p => p.id === receiverId)
    );

    const newMessage: Message = {
        id: `m${Date.now()}`,
        senderId,
        text,
        timestamp: new Date().toISOString(),
    };

    if (conversation) {
        conversation.messages.push(newMessage);
    } else {
        const sender = mockUsers.find(u => u.id === senderId);
        const receiver = mockUsers.find(u => u.id === receiverId);
        if(!sender || !receiver) throw new Error("User not found");
        const newConversation: Conversation = {
            id: `c${Date.now()}`,
            participants: [sender, receiver],
            messages: [newMessage],
        };
        mockConversations.push(newConversation);
        conversation = newConversation;
    }
    return { newMessage, conversation };
};


export const api = {
  getTopTutors: async (): Promise<Tutor[]> => {
    await delay(500);
    return allTutorsData.slice(0, 4);
  },
  searchTutors: async (query: { location?: string; subject?: string; offset?: number; limit?: number; minRate?: number; maxRate?: number; minExperience?: number; }): Promise<{tutors: Tutor[], hasMore: boolean}> => {
    await delay(800);
    let filteredTutors = allTutorsData;

    if (query.location) {
      filteredTutors = filteredTutors.filter(t => t.location.toLowerCase().includes(query.location!.toLowerCase()));
    }
    if (query.subject) {
      filteredTutors = filteredTutors.filter(t => t.subjects.some(s => s.toLowerCase().includes(query.subject!.toLowerCase())));
    }
    if (query.minRate) {
        filteredTutors = filteredTutors.filter(t => t.hourlyRate >= query.minRate!);
    }
    if (query.maxRate) {
        filteredTutors = filteredTutors.filter(t => t.hourlyRate <= query.maxRate!);
    }
    if (query.minExperience) {
        filteredTutors = filteredTutors.filter(t => t.experience >= query.minExperience!);
    }

    const offset = query.offset || 0;
    const limit = query.limit || 4;
    const paginatedTutors = filteredTutors.slice(offset, offset + limit);
    const hasMore = (offset + limit) < filteredTutors.length;
    
    return { tutors: paginatedTutors, hasMore };
  },
  getTutorById: async (id: string): Promise<Tutor | undefined> => {
    await delay(600);
    return allTutorsData.find(t => t.id === id);
  },
  getReviews: async (): Promise<Review[]> => {
    await delay(300);
    return allReviewsData;
  },
  registerUser: async (userData: any): Promise<{ success: boolean; message: string }> => {
    await delay(1000);
    console.log('Registering user:', userData);
    return { success: true, message: `Registration successful for ${userData.name}!` };
  },
  loginUser: async (credentials: any): Promise<{ success: boolean; message: string; token?: string; user?: User | Tutor }> => {
    await delay(1000);
    console.log('Logging in with:', credentials);

    if (credentials.email === 'eleanor@example.com' && credentials.password === 'password') {
      const tutorUser = allTutorsData.find(t => t.id === '1');
      return { success: true, message: 'Tutor login successful!', token: 'fake-jwt-token-tutor', user: tutorUser };
    }
    if (credentials.email === 'test@example.com' && credentials.password === 'password') {
      return { success: true, message: 'Login successful!', token: 'fake-jwt-token', user: mockUsers[0] };
    }
    return { success: false, message: 'Invalid email or password.' };
  },
  updateUserProfile: async (userId: string, updates: Partial<Tutor>): Promise<{ success: boolean; user?: User | Tutor }> => {
    await delay(500);
    const tutorIndex = allTutorsData.findIndex(t => t.id === userId);
    if (tutorIndex !== -1) {
        const updatedTutor = { ...allTutorsData[tutorIndex], ...updates };
        allTutorsData[tutorIndex] = updatedTutor;
        
        const userIndexInMocks = mockUsers.findIndex(u => u.id === userId);
        if (userIndexInMocks !== -1) {
            mockUsers[userIndexInMocks] = { ...mockUsers[userIndexInMocks], name: updatedTutor.name, imageUrl: updatedTutor.imageUrl };
        }
        return { success: true, user: updatedTutor };
    }

    const userIndex = mockUsers.findIndex(u => u.id === userId);
    if (userIndex !== -1) {
        const updatedUser = { ...mockUsers[userIndex], ...updates };
        mockUsers[userIndex] = updatedUser as User;
        return { success: true, user: updatedUser };
    }

    return { success: false };
  },
  sendMessage: async (data: { senderId: string; receiverId: string; text: string }): Promise<Message> => {
    await delay(200); // Shorter delay for sending
    const { newMessage, conversation } = addMessage(data);
    messagingService.notifyNewMessage({ message: newMessage, conversationId: conversation.id });
    return newMessage;
  },
  getConversations: async(userId: string): Promise<Conversation[]> => {
    await delay(500);
    return mockConversations
        .filter(c => c.participants.some(p => p.id === userId))
        .sort((a,b) => new Date(b.messages[b.messages.length - 1].timestamp).getTime() - new Date(a.messages[a.messages.length - 1].timestamp).getTime());
  },
  getConversationById: async(conversationId: string): Promise<Conversation | undefined> => {
    await delay(400);
    return mockConversations.find(c => c.id === conversationId);
  },
  getTutorIdFromMessage: (message: Message): string | undefined => {
    const conversation = mockConversations.find(c => c.messages.some(m => m.id === message.id));
    const tutorParticipant = conversation?.participants.find(p => !p.id.includes('student'));
    return tutorParticipant?.id;
  },
  internal_addMessage: async (data: { senderId: string; receiverId: string; text: string }): Promise<RealtimeMessagePayload> => {
     await delay(100);
     const { newMessage, conversation } = addMessage(data);
     return { message: newMessage, conversationId: conversation.id };
  },
};